INSERT INTO tb_material(name) VALUES ('Aluminio');
INSERT INTO tb_material(name) VALUES ('Antenas');
INSERT INTO tb_material(name) VALUES ('Árvores');
INSERT INTO tb_material(name) VALUES ('Baterias automotivas');
INSERT INTO tb_material(name) VALUES ('Baterias celular');
INSERT INTO tb_material(name) VALUES ('Bombonas');
INSERT INTO tb_material(name) VALUES ('Cerâmica');
INSERT INTO tb_material(name) VALUES ('Eletrônicos');
INSERT INTO tb_material(name) VALUES ('Embalagem Longa Vida');
INSERT INTO tb_material(name) VALUES ('Entulhos');
INSERT INTO tb_material(name) VALUES ('Ferro');
INSERT INTO tb_material(name) VALUES ('Fios, cabos elétricos');
INSERT INTO tb_material(name) VALUES ('Gorduras');
INSERT INTO tb_material(name) VALUES ('Lâmpadas');
INSERT INTO tb_material(name) VALUES ('Outros');
INSERT INTO tb_material(name) VALUES ('Papelão');
INSERT INTO tb_material(name) VALUES ('Pilhas');
INSERT INTO tb_material(name) VALUES ('Plásticos');
INSERT INTO tb_material(name) VALUES ('Pneus');
INSERT INTO tb_material(name) VALUES ('Roupas');
INSERT INTO tb_material(name) VALUES ('Vidros');

INSERT INTO tb_user(name, email, password) VALUES ('Anderson Martins', 'anderson@gmail.com', '$2a$10$spIwnDspZDu4gpbkOxDa4uncgDlapO28oJ/JsZULMoiun7sCL7Ozq');
INSERT INTO tb_role(authority) VALUES('ROLE_ADMIN');

INSERT INTO tb_user_role(user_id, role_id) VALUES(1, 1);

INSERT INTO tb_company(name, phone) VALUES ('TIM - Loja Campinas', '19984324567');
INSERT INTO tb_company(name, phone) VALUES ('C&A - Centro Campinas', '1121620063');
INSERT INTO tb_company(name, phone) VALUES ('Carrefour', '1932519820');
INSERT INTO tb_company(name, phone) VALUES ('Tayo Ouro Verde', '1932661333');
INSERT INTO tb_company(name, phone) VALUES ('Ecoponto 2 Quintal', '9235844183');
INSERT INTO tb_company(name, phone) VALUES ('Cooperativa São Bernado', '1155745045');
INSERT INTO tb_company(name, phone) VALUES ('Coop Nossa Sr. Aparecida - Projeto Reciclar', '19981951795');
INSERT INTO tb_company(name, phone) VALUES ('Pneus Pirelli Campinas', '1937283200');
INSERT INTO tb_company(name, phone) VALUES ('Andras Diesel Peças LTDA Me', '1932279913');
INSERT INTO tb_company(name, phone) VALUES ('Campinas Bateria', '1996023382');
INSERT INTO tb_company(name, phone) VALUES ('Supermercado Pague Menos', '1937383040');
INSERT INTO tb_company(name, phone) VALUES ('Led Luz Iluminação LTDA', '1932544402');
INSERT INTO tb_company(name, phone) VALUES ('C&C - Loja Saudade', '1140010100');
INSERT INTO tb_company(name) VALUES ('Ecoponto Jardim São Gabriel');
INSERT INTO tb_company(name, phone) VALUES ('Tenda Atacado Campinas', '1937724999');
INSERT INTO tb_company(name, phone) VALUES ('Casas Bahia', '1937316000');
INSERT INTO tb_company(name) VALUES ('Ecoponto Parque Via Norte');
INSERT INTO tb_company(name, phone) VALUES ('Suleste', '1932425154');
INSERT INTO tb_company(name) VALUES ('Ecoponto Pneus e Lixo Eletrônico');
INSERT INTO tb_company(name, phone) VALUES ('Jhs Auto Peças LTDA', '1938873447');
INSERT INTO tb_company(name) VALUES ('Ecoponto Vila União');
INSERT INTO tb_company(name) VALUES ('Ecoponto Jardim Eulina');
INSERT INTO tb_company(name) VALUES ('Ecoponto Jardim Pacaembu');
INSERT INTO tb_company(name) VALUES ('Ecoponto Vida Nova');
INSERT INTO tb_company(name) VALUES ('Ecoponto Barão Geraldo');

INSERT INTO tb_address(company_id, street, number, cep, city, state) VALUES (1, 'Rua Treze de Maio', 493, '13010071', 'Campinas', 'SP');
INSERT INTO tb_address(company_id, street, number, cep, city, state) VALUES (2, 'Rua Treze de Maio', 520, '13010071', 'Campinas', 'SP');
INSERT INTO tb_address(company_id, street, number, cep, city, state) VALUES (3, 'Avenida José de Souza Campos', 690, '13092123', 'Campinas', 'SP');
INSERT INTO tb_address(company_id, street, number, cep, city, state) VALUES (4, 'Avenida Itamarati', 299, '13054670', 'Campinas', 'SP');
INSERT INTO tb_address(company_id, street, number, cep, city, state) VALUES (5, 'Rua Antonio Cremasco', 165, '13274465', 'Valinhos', 'SP');
INSERT INTO tb_address(company_id, street, number, cep, city, state) VALUES (6, 'Avenida Prefeito Faria Lima', 630, '13036220', 'Campinas', 'SP');
INSERT INTO tb_address(company_id, street, number, cep, city, state) VALUES (7, 'Rua Alaide Nascimento de Lemos', 300, '13100453', 'Campinas', 'SP');
INSERT INTO tb_address(company_id, street, number, cep, city, state) VALUES (8, 'Avenida Jhon Boyd Dunlop', 6800, '13034685', 'Campinas', 'SP');
INSERT INTO tb_address(company_id, street, number, cep, city, state) VALUES (9, 'Rua Maria Gomes Carvalho', 11, '13059087', 'Campinas', 'SP');
INSERT INTO tb_address(company_id, street, number, cep, city, state) VALUES (10, 'Rua Altino Arantes', 1250, '13051110', 'Campinas', 'SP');
INSERT INTO tb_address(company_id, street, number, cep, city, state) VALUES (11, 'Avenida Baden Powell', 2026, '13040093', 'Campinas', 'SP');
INSERT INTO tb_address(company_id, street, number, cep, city, state) VALUES (12, 'Rua Dr. Emilio Ribas', 1085, '13025142', 'Campinas', 'SP');
INSERT INTO tb_address(company_id, street, number, cep, city, state) VALUES (13, 'Avenida Saudade', 1214, '13041670', 'Campinas', 'SP');
INSERT INTO tb_address(company_id, street, number, cep, city, state) VALUES (14, 'Rua José Martins Lourenço', 140, '13045310', 'Campinas', 'SP');
INSERT INTO tb_address(company_id, street, number, cep, city, state) VALUES (15, 'Rua Padre Bernado da Silva', 1111, '13030710', 'Campinas', 'SP');
INSERT INTO tb_address(company_id, street, number, cep, city, state) VALUES (16, 'Rua Costa Aguiar', 348, '13010061', 'Campinas', 'SP');
INSERT INTO tb_address(company_id, street, number, cep, city, state) VALUES (17, 'Rua dos Cambarás', 200, '13064740', 'Campinas', 'SP');
INSERT INTO tb_address(company_id, street, number, cep, city, state) VALUES (18, 'Avenida Gov. Pedro de Toleto', 2046, '13070715', 'Campinas', 'SP');
INSERT INTO tb_address(company_id, street, number, cep, city, state) VALUES (19, 'Avenida Pref. Faria Lima', 630, '13036220', 'Campinas', 'SP');
INSERT INTO tb_address(company_id, street, number, cep, city, state) VALUES (20, 'Rua Marcelina Ramos Meira', 86, '13185250', 'Campinas', 'SP');
INSERT INTO tb_address(company_id, street, number, cep, city, state) VALUES (21, 'Rua Manoel Gomes Ferreira', 42, '13060523', 'Campinas', 'SP');
INSERT INTO tb_address(company_id, street, number, cep, city, state) VALUES (22, 'Avenida Mal. Rondon', 2296, '13063490', 'Campinas', 'SP');
INSERT INTO tb_address(company_id, street, number, cep, city, state) VALUES (23, 'Rua Dante Suriani', 2382, '13033160', 'Campinas', 'SP');
INSERT INTO tb_address(company_id, street, cep, city, state) VALUES (24, 'Rua Lídia Martins de Assis', '13057558', 'Campinas', 'SP');
INSERT INTO tb_address(company_id, street, number, cep, city, state) VALUES (25, 'Avenida Santa Isabel', 2300, '13084012', 'Campinas', 'SP');

INSERT INTO tb_company_material(company_id, material_id) VALUES (1, 5);
INSERT INTO tb_company_material(company_id, material_id) VALUES (1, 8);
INSERT INTO tb_company_material(company_id, material_id) VALUES (1, 15);
INSERT INTO tb_company_material(company_id, material_id) VALUES (2, 5);
INSERT INTO tb_company_material(company_id, material_id) VALUES (2, 8);
INSERT INTO tb_company_material(company_id, material_id) VALUES (2, 20);
INSERT INTO tb_company_material(company_id, material_id) VALUES (3, 5);
INSERT INTO tb_company_material(company_id, material_id) VALUES (3, 16);
INSERT INTO tb_company_material(company_id, material_id) VALUES (3, 14);
INSERT INTO tb_company_material(company_id, material_id) VALUES (4, 14);
INSERT INTO tb_company_material(company_id, material_id) VALUES (5, 21);
INSERT INTO tb_company_material(company_id, material_id) VALUES (5, 9);
INSERT INTO tb_company_material(company_id, material_id) VALUES (6, 9);
INSERT INTO tb_company_material(company_id, material_id) VALUES (6, 18);
INSERT INTO tb_company_material(company_id, material_id) VALUES (7, 18);
INSERT INTO tb_company_material(company_id, material_id) VALUES (7, 6);
INSERT INTO tb_company_material(company_id, material_id) VALUES (7, 9);
INSERT INTO tb_company_material(company_id, material_id) VALUES (7, 13);
INSERT INTO tb_company_material(company_id, material_id) VALUES (8, 19);
INSERT INTO tb_company_material(company_id, material_id) VALUES (9, 4);
INSERT INTO tb_company_material(company_id, material_id) VALUES (10, 4);
INSERT INTO tb_company_material(company_id, material_id) VALUES (11, 5);
INSERT INTO tb_company_material(company_id, material_id) VALUES (11, 8);
INSERT INTO tb_company_material(company_id, material_id) VALUES (11, 15);
INSERT INTO tb_company_material(company_id, material_id) VALUES (12, 14);
INSERT INTO tb_company_material(company_id, material_id) VALUES (13, 14);
INSERT INTO tb_company_material(company_id, material_id) VALUES (14, 2);
INSERT INTO tb_company_material(company_id, material_id) VALUES (14, 3);
INSERT INTO tb_company_material(company_id, material_id) VALUES (14, 13);
INSERT INTO tb_company_material(company_id, material_id) VALUES (14, 21);
INSERT INTO tb_company_material(company_id, material_id) VALUES (14, 8);
INSERT INTO tb_company_material(company_id, material_id) VALUES (15, 8);
INSERT INTO tb_company_material(company_id, material_id) VALUES (16, 8);
INSERT INTO tb_company_material(company_id, material_id) VALUES (17, 8);
INSERT INTO tb_company_material(company_id, material_id) VALUES (17, 10);
INSERT INTO tb_company_material(company_id, material_id) VALUES (17, 7);
INSERT INTO tb_company_material(company_id, material_id) VALUES (17, 12);
INSERT INTO tb_company_material(company_id, material_id) VALUES (18, 16);
INSERT INTO tb_company_material(company_id, material_id) VALUES (18, 9);
INSERT INTO tb_company_material(company_id, material_id) VALUES (19, 19);
INSERT INTO tb_company_material(company_id, material_id) VALUES (19, 8);
INSERT INTO tb_company_material(company_id, material_id) VALUES (20, 4);
INSERT INTO tb_company_material(company_id, material_id) VALUES (21, 14);
INSERT INTO tb_company_material(company_id, material_id) VALUES (21, 1);
INSERT INTO tb_company_material(company_id, material_id) VALUES (21, 3);
INSERT INTO tb_company_material(company_id, material_id) VALUES (21, 7);
INSERT INTO tb_company_material(company_id, material_id) VALUES (21, 10);
INSERT INTO tb_company_material(company_id, material_id) VALUES (21, 13);
INSERT INTO tb_company_material(company_id, material_id) VALUES (21, 19);
INSERT INTO tb_company_material(company_id, material_id) VALUES (21, 15);
INSERT INTO tb_company_material(company_id, material_id) VALUES (22, 14);
INSERT INTO tb_company_material(company_id, material_id) VALUES (22, 1);
INSERT INTO tb_company_material(company_id, material_id) VALUES (22, 3);
INSERT INTO tb_company_material(company_id, material_id) VALUES (22, 7);
INSERT INTO tb_company_material(company_id, material_id) VALUES (22, 10);
INSERT INTO tb_company_material(company_id, material_id) VALUES (22, 13);
INSERT INTO tb_company_material(company_id, material_id) VALUES (22, 19);
INSERT INTO tb_company_material(company_id, material_id) VALUES (22, 15);
INSERT INTO tb_company_material(company_id, material_id) VALUES (23, 14);
INSERT INTO tb_company_material(company_id, material_id) VALUES (23, 1);
INSERT INTO tb_company_material(company_id, material_id) VALUES (23, 3);
INSERT INTO tb_company_material(company_id, material_id) VALUES (23, 7);
INSERT INTO tb_company_material(company_id, material_id) VALUES (23, 10);
INSERT INTO tb_company_material(company_id, material_id) VALUES (23, 13);
INSERT INTO tb_company_material(company_id, material_id) VALUES (23, 19);
INSERT INTO tb_company_material(company_id, material_id) VALUES (23, 15);
INSERT INTO tb_company_material(company_id, material_id) VALUES (24, 14);
INSERT INTO tb_company_material(company_id, material_id) VALUES (24, 1);
INSERT INTO tb_company_material(company_id, material_id) VALUES (24, 3);
INSERT INTO tb_company_material(company_id, material_id) VALUES (24, 7);
INSERT INTO tb_company_material(company_id, material_id) VALUES (24, 10);
INSERT INTO tb_company_material(company_id, material_id) VALUES (24, 13);
INSERT INTO tb_company_material(company_id, material_id) VALUES (24, 19);
INSERT INTO tb_company_material(company_id, material_id) VALUES (24, 15);
INSERT INTO tb_company_material(company_id, material_id) VALUES (25, 14);
INSERT INTO tb_company_material(company_id, material_id) VALUES (25, 1);
INSERT INTO tb_company_material(company_id, material_id) VALUES (25, 3);
INSERT INTO tb_company_material(company_id, material_id) VALUES (25, 7);
INSERT INTO tb_company_material(company_id, material_id) VALUES (25, 10);
INSERT INTO tb_company_material(company_id, material_id) VALUES (25, 13);
INSERT INTO tb_company_material(company_id, material_id) VALUES (25, 19);
INSERT INTO tb_company_material(company_id, material_id) VALUES (25, 15);










